apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: tomcat
  name: tomcat
spec: {}
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: tomcat
  labels:
    name: tomcat
spec:
  output:
    to:
      kind: ImageStreamTag
      name: tomcat:latest
  resources: {}
  source:
    contextDir: "tomcat/"
    type: Git
    git:
      uri: 'https://github.com/taabich/httpd-openshift'
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: "tomcat/DockerFile"
