apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: tomcat-server
  labels: 
    app: tomcat-server

objects:
- kind: ImageStream
  apiVersion: image.openshift.io/v1
  metadata:
    annotations:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec: {}
- kind: "BuildConfig"
  apiVersion: build.openshift.io/v1
  metadata:
    name: ${APP_NAME}
    labels:
      app: ${APP_NAME}
  spec:
    type: Git
    contextDir: "tomcat9/"
    source: 
      git:
        uri: "${APP_GIT_URL}"
    strategy:
      type: Docker
      dockerStrategy:
        dockerfilePath: Dockerfile
    output: 
      to:
        kind: "ImageStreamTag"
        name: "${APP_NAME}:latest"
        

- kind: Deployment
  apiVersion: apps/v1
  metadata:
    name: ${APP_NAME}
    labels:
      app: ${APP_NAME}
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: ${APP_NAME}  
    template: 
      metadata:
        labels:
          name: ${APP_NAME}
          app: ${APP_NAME}
      spec:
        containers:
        - env:
            - name: TOMCAT_USERNAME
            - name: TOMCAT_PASSWORD
          name: ${APP_NAME}
          image: ${APP_NAME}:latest
          ports:
              - containerPort: 8009
                protocol: TCP
              - containerPort: 8443
                protocol: TCP
          resources: {}

    triggers:
      - type: "ConfigChange" 
      - imageChangeParams:
          automatic: true
          containerNames:
            - ${APP_NAME}
          from:
            kind: "ImageStreamTag"
            name: ${APP_NAME}:latest
        type: ImageChange

- kind: Service
  apiVersion: v1
  metadata:
    annotations:
    name: ${APP_NAME}
    labels:
      app: ${APP_NAME}
  spec:
    ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    selector:
      app: ${APP_NAME}
    type: ClusterIP
    sessionAffinity: None
- kind: Route
  apiVersion: route.openshift.io/v1
  metadata:
    name: ${APP_NAME}
    labels:
      app: ${APP_NAME}
    annotations:
  spec:
    to:
      kind: Service
      name: ${APP_NAME}
      weight: 100
    port:
      targetPort: 8080-tcp
  wildcardPolicy: None
parameters:
- name: APP_NS
  displayName: Application Namespace
  description: Nama aplikasi dan namespace
  value: tomcat
- name: APP_NAME
  displayName: Application Name
  description: Nama aplikasi dan namespace
  value: tomcat-server
  required: true
- name: APP_GIT_URL
  displayName: Application Source Git URL
  description: The Git URL of the application source code
  required: true
  value: https://github.com/taabich/httpd-openshift
- name: SECRET
  displayName: Webhook Secret
  description: Secret for webhooks
  value: tomcat
